# Generated by Django 5.2.6 on 2025-09-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('talla_inicio', models.CharField(max_length=50)),
                ('talla_fin', models.CharField(max_length=50)),
                ('total_piezas', models.IntegerField()),
                ('cliente', models.CharField(max_length=100)),
                ('foto_modelo', models.ImageField(upload_to='ordenes/fotos/')),
                ('especificaciones_pdf', models.FileField(upload_to='ordenes/pdfs/')),
            ],
        ),
    ]
